### ISSUE TITLE
能否请求添加ipv6支持

### ISSUE THREAD

**Issue by kunwu3** [Spedoske/CloudflareScanner#1]
想在学校里用

**Comment by kunwu3** [comment]
其他项目中的类似功能：[XX-Net](https://github.com/XX-net/XX-Net/wiki/%E2%80%9C%E9%AB%98%E7%BA%A7%E2%80%9D%E9%A1%B5%E9%9D%A2)
希望有帮助

**Comment by XIU2** [comment]
@kunwu3 你可以试试我 Fork 的这个版本，刚刚 v1.3.6 版本添加了 IPv6 支持。

- **https://github.com/XIU2/CloudflareSpeedTest**
_🌩 测试 Cloudflare CDN 所有 IP 的延迟和速度，获取最快 IP！_

****

1. **新增** IPv6 支持（延迟测速+下载测速）。  
`因为 IPv6 IP 太多了（约 294 亿），而且 Cloudflare CDN 目前只用了极小一部分（约 400 万），所以目前是采用 IP 段子网随机测速。`
`因为 Cloudflare 没有提供当前正在使用的 IPv6 IP段（绝大部分为闲置状态），所以 ipv6.txt 文件内并不是全部 IP 段，但也差不多了。`

**Comment by kunwu3** [comment]
> @kunwu3 你可以试试我 Fork 的这个版本，刚刚 v1.4.0 版本添加了 IPv6 支持。
> 
> * **https://github.com/XIU2/CloudflareSpeedTest**
>   _🌩 测试 Cloudflare CDN 延迟和速度，获取最快 IP (IPv4+IPv6)！_
> 
> 1. **新增** IPv6 支持（延迟测速+下载测速）。
>    `因为 IPv6 IP 太多了（约 294 亿），而且 Cloudflare CDN 目前只用了极小一部分（约 400 万），所以目前是采用 IP 段子网随机测速。`
>    `因为 Cloudflare 没有提供当前正在使用的 IPv6 IP段（绝大部分为闲置状态），所以 ipv6.txt 文件内并不是全部 IP 段，但也差不多了。`

感谢 目前能用的ip基本几种在2606:4700:
